version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
    open-pull-requests-limit: 5
