name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-yarn:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 16.18

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build project
        run: |
          yarn build

  build-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build .
